### PR TITLE
Allow the Creation of Configuration Extensions

### PR DESCRIPTION
**Pull request by maennchen**
This PR needs the PR https://github.com/willdurand/Hateoas/pull/234 to be merged.

### CODE REVIEW

**Comment by willdurand** [comment]
So there is 2.10.0 now: https://github.com/willdurand/Hateoas/releases/tag/2.10.0.

**Comment by maennchen** [comment]
Is it possible to drop PHP 5.4 support? Otherwise I'd have to fix a few syntax errors...

#55

**Comment by maennchen** [comment]
@willdurand: Ping

**Comment by maennchen** [comment]
@willdurand: Would you be able to tag the newest master?

**Pull request merged**
