### PR TITLE
Fix symfony3 "security.context" deprecation

### PR DESCRIPTION
**Pull request by jaimeMerino**
symfony3 "security.context" deprecation fix

### CODE REVIEW

**Comment by willdurand** [comment]
Could you please not update the composer file? And also, write a meaningful commit message? Thanks

**Comment by jaimeMerino** [comment]
composer and commit message updated. ;)

**Comment by willdurand** [comment]
Could you please squash your commits?

**Comment by jaimeMerino** [comment]
done!

**Comment by willdurand** [comment]
thank you!

**Pull request merged**
