### PR TITLE
add option to disable twig extension registered by bundle

### PR DESCRIPTION
**Pull request by ahilles107**

### CODE REVIEW

**Comment by ahilles107** [comment]
Hey guys, is this wrong approach?

**Comment by adrienbrault** [comment]
This looks fine, but what about making the twig extension private ?

**Comment by ahilles107** [comment]
in Symfony 4.0 it will be private by default (as it't not set to public). But changing it now would be BC break for some users. This is why i set it in configuration to be enabled by default.

**Comment by ahilles107** [comment]
@adrienbrault - can we merge it?

**Comment by adrienbrault** [comment]
👍

**Comment by willdurand** [comment]
thanks!

**Pull request merged**
