### PR TITLE
Make doctrine/annotations optional + drop PHP < 8.1

### PR DESCRIPTION
**Pull request by W0rma**
Follow-up of https://github.com/willdurand/Hateoas/pull/334

### CODE REVIEW

**Comment by W0rma** [comment]
Jobs with symfony ^3.0 and ^4.0 fail if `doctrine/annotations` package is not installed.
Looks like this is because `jms/serializer-bundle:4.2` does not really work without this package.

Tests with serializer-bundle v3 and v5 look fine.

@goetas Do you think it's worth the effort to look into the issue with v4.2 or is it sufficient to have the tests without annotations only for symfony ^5.0 and higher?

**Comment by goetas** [comment]
Running tests on most recent symfony versions is more than acceptable.

I would not mind dropping old php and symfony versions as well (if it helps you here)

**Comment by goetas** [comment]
Hi, thanks a lot, I will check it later in the evening

**Comment by W0rma** [comment]
Tests are green.

All supported symfony versions are still tested.
The tests without `doctrine/annotations` package are only executed with symfony 5 and higher

**Comment by goetas** [comment]
I could not spot anything wrong, great work! thank you!

**Pull request merged**
