### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by thomaroger**
https://github.com/schmittjoh/JMSSerializerBundle/commit/0be35615b5bae1ce42567244a321aa1be3ed0280

### CODE REVIEW

**Comment by piotrantosik** [comment]
:+1:

**Comment by piotrantosik** [comment]
tests fail, jms/serializer 1.0.0 requires php >=5.4.0...
should be:
```
"jms/serializer-bundle": "~0.13.0"
```

**Comment by willdurand** [comment]
we can also require `5.4+`

**Comment by chroder** [comment]
:+1:

**Comment by willdurand** [comment]
done by #43

**Comment by willdurand** [comment]
Version [1.0](https://github.com/willdurand/BazingaHateoasBundle/releases/tag/1.0.0) of this bundle is released!

**Pull request closed without merging**
