### PR TITLE
Upgrade JMS Serializer to v1.0

### PR DESCRIPTION
**Pull request by peterrehm**

### CODE REVIEW

**Comment by peterrehm** [comment]
Just updated the PHP requirements and the travis settings. Tests wont pass unless a new release of Hateoas will be tagged.

**Comment by willdurand** [comment]
done by #43

**Comment by willdurand** [comment]
(but thanks)

**Comment by willdurand** [comment]
Version [1.0](https://github.com/willdurand/BazingaHateoasBundle/releases/tag/1.0.0) of this bundle is released!

**Comment by peterrehm** [comment]
Awesome, thanks!

**Pull request closed without merging**
