### PR TITLE
Test against php 7.3 and php 7.4

### PR DESCRIPTION
**Pull request by W0rma**

### CODE REVIEW

**Comment by W0rma** [comment]
`jms/serializer` < 3.2 causes some deprecations on php7.4. `willdurand/hateoas` already bumped the version of `jms/serializer` to ^3.2.

@goetas Maybe you can tag a new release of https://github.com/willdurand/Hateoas - then we can bump the version of 'willdurand/hateoas` to the new release and thus fix the php7.4 deprecations.

**Comment by goetas** [comment]
>  Maybe you can tag a new release of https://github.com/willdurand/Hateoas - then we can bump the version of 'willdurand/hateoas` to the new release and thus fix the php7.4 deprecations. 

done

**Comment by W0rma** [comment]
Thank you. Tests are green now

**Comment by goetas** [comment]
Thanks!

**Pull request merged**
